### ISSUE TITLE
Does fslpy depend on rtree?

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fslpy#11]
I recently came across [this issue comment](https://github.com/pauldmccarthy/fslpy/issues/7#issuecomment-559724269), stating that fslpy does not in fact depend on rtree. Yet, I see two import calls to it in the package:

```
chymera@silenthost ~/src/fslpy $ ag rtree
README.rst
57:- ``trimesh``/``rtree``: The `fsl.data.mesh.TriangleMesh <fsl/data/mesh.py>`_
90:The ``rtree`` library assumes that ``libspatialindex`` is installed on

requirements-extra.txt
4:rtree>=0.8.3

CHANGELOG.rst
1171:  ``rtree`` are now listed separately, so ``fslpy`` can be used without them

setup.cfg
12:    meshtest:   Requires trimesh and rtree

tests/test_mesh.py
282:    # Make sure trimesh and rtree
287:    import rtree
289:    mods = ['trimesh', 'rtree']

fsl/data/mesh.py
513:        If the ``trimesh`` or ``rtree`` libraries are not available, this
518:        # trimesh is an optional dependency - rtree
525:            import rtree   # noqa
```

Just asking to clarify.
If those import calls are superfluous and could be removed, that would simplify the dependency graph in any case.

**Comment by pauldmccarthy** [comment]
This is covered in the README:

> All of the core dependencies of fslpy are listed in the requirements.txt file.
> 
> Some extra dependencies are listed in requirements-extra.txt which provide addditional functionality:
>
>  - trimesh/rtree: The fsl.data.mesh.TriangleMesh class has some methods which use trimesh to perform geometric queries on the mesh.
