### ISSUE TITLE
How to use the libraries

### ISSUE THREAD

**Issue by stavrizinonos** [pauldmccarthy/fslpy#13]
Hi, is there an example on how to use this library?
i want to use FAST segmentation and the registration to MNI space using fslpy, but there are no any examples using this package so i can based on them. Can you provide me with an example in python code? Thank you.

**Comment by pauldmccarthy** [comment]
Hi @stavrizinonos, API documentation (with a couple of examples) can be found here: https://open.win.ox.ac.uk/pages/fsl/fslpy/fsl.wrappers.html

There are no specific examples on using the `fsl.wrappers` functions, but most of them provide an interface which is very similar to the command-line interface of the underlying FSL tool. So, for example, to perform FAST segmentation on a T1 image, you can do something like this:

```python
import nibabel as nib
from fsl.wrappers import fast

fast('T1.nii.gz', 'T1_fast')
pve0 = nib.load('T1_fast_pve_0.nii.gz')
```

You can also pass in-memory nibabel images as inputs, and have the outputs automatically loaded by using the `fsl.wrappers.LOAD` symbol - this is all described in the afore-mentioned API documentation.

**Comment by stavrizinonos** [comment]
Thanks for this. But, when i try to run this i get a message like "FSLNotPresent: $FSLDIR is not set - FSL cannot be found!".
Why am i getting this? Isn't FSL automatically installed when i do 'pip install fslpy'?

**Comment by pauldmccarthy** [comment]
No, it's the other way around - `fslpy` is a library which is installed as part of FSL (and can be installed independently of FSL, which is what you have done here).

**Comment by giemmecci** [comment]
> No, it's the other way around - `fslpy` is a library which is installed as part of FSL (and can be installed independently of FSL, which is what you have done here).

Hi, I'm a bit confused: do we need to have FSL installed in order to run fslpy? Thanks!

**Comment by pauldmccarthy** [comment]
> Hi, I'm a bit confused: do we need to have FSL installed in order to run fslpy? Thanks!

No, you can install fslpy independently of FSL. But if you do so, certain features will not be usable, e.g. the `fsl.wrappers` functions.
