### ISSUE TITLE
$FSLDIR is not set

### ISSUE THREAD

**Issue by meredithefay** [pauldmccarthy/fslpy#20]
Hi, 

I'm trying to use fslpy to run BET on a series of images. I'm using PyCharm as an IDE and have Python 3.9 installed. I installed the latest version of fslpy using a pip command. I imported fslpy in the following way:

```
from fsl.wrappers import bet
```

My line of code is placed within a loop of a series of images and is as follows:

```
bet(file, new_name)
```

When I run the code, I receive the following error:

```
Traceback (most recent call last):
  File "/Users/mef72/Documents/PycharmProjects/Putamen/run_FSL_BET.py", line 50, in <module>
    bet(file, new_name)
  File "/Users/mef72/Documents/PycharmProjects/Putamen/venv/lib/python3.9/site-packages/fsl/wrappers/wrapperutils.py", line 1282, in wrapper
    result = fot(*args, **kwargs)
  File "/Users/mef72/Documents/PycharmProjects/Putamen/venv/lib/python3.9/site-packages/fsl/wrappers/wrapperutils.py", line 921, in __call__
    result = func(*args, **kwargs)
  File "/Users/mef72/Documents/PycharmProjects/Putamen/venv/lib/python3.9/site-packages/fsl/wrappers/wrapperutils.py", line 214, in wrapper
    return runner(cmd,
  File "/Users/mef72/Documents/PycharmProjects/Putamen/venv/lib/python3.9/site-packages/fsl/utils/run.py", line 397, in runfsl
    raise FSLNotPresent('$FSLDIR is not set - FSL cannot be found!')
fsl.utils.run.FSLNotPresent: $FSLDIR is not set - FSL cannot be found!
```

I tried setting a path variable in the terminal of PyCharm but no luck. Passing an exception avoids the error but results in no brain extraction. Thanks for any thoughts.

Meredith

**Comment by pauldmccarthy** [comment]
Hi @meredithefay, I'm guessing you started PyCharm via a desktop shortcut - it is not being executed with the same environment variables that are set when you open a terminal.

Probably the cleanest solution for you is to add `$FSLDIR` (and any other variables you need) to your PyCharm environment configuration as outlined at https://stackoverflow.com/a/42708480 (have a look at the other answers to that post for some alternative options).

**Comment by meredithefay** [comment]
Hi @pauldmccarthy, 

Thank you so much, unfortunately I'm new to this and think I need a little more help. I am starting PyCharm via a desktop shortcut. I tried both the first option in the linked StackOverflow post (using the run configurations profile) and the second (adding an environment .env file). For example, here's my .env file contents:

```
FSLDIR=/Users/mef72/Documents/PycharmProjects/Putamen/venv/lib/python3.9/site-packages/fsl
DEBUG=1
```

When using the first method, I also used the FSLDIR variable and filepath in the same way.

I receive the same error with each:

```
FileNotFoundError: FSL tool bet not found (checked /Users/mef72/Documents/PycharmProjects/Putamen/venv/lib/python3.9/site-packages/fsl/bin)
```

Placing all contents of the fsl library into a bin subdirectory gets rid of this error, but produces another:

```
ModuleNotFoundError: No module named 'fsl.wrappers'
```

I wasn't able to find a helpful StackOverflow post describing why "/bin" is appended to my path variables. Do you have any suggestions for what I'm doing wrong?

Thank you!

Meredith

**Comment by pauldmccarthy** [comment]
@meredithefay Have you installed FSL? Installing fslpy does not install the FSL tools - the `fsl.wrappers` package just provides wrapper functions to call FSL commands, but does not provide the commands themselves.

You will need to install FSL separately, following the instructions at https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation

After you have installed FSL, you will probably still need to tell PyCharm where FSL is installed - by default FSL will be installed to `$HOME/fsl`, so you will need to set `FSLDIR=/Users/mef72/fsl`

And FSL comes with its own Python environment, with fslpy already installed into it, so within PyCharm you should be able to select `/Users/mef72/fsl/` as an environment, and/or `/Users/mef72/fsl/bin/python` as the interpreter to use. I am not particularly familiar with PyCharm, but I remember it being fairly straightforward to specify the environment/interpreter that should be used for a given PyCharm project.

**Comment by meredithefay** [comment]
@pauldmccarthy, thank you, I knew I was doing something silly. I do have FSL installed and changing my environment.env file directly to FSL (see below) worked. Thank you!

```
FSLDIR=/Users/mef72/fsl
DEBUG=1
```
