### ISSUE TITLE
vest.py test error: RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fslpy#3]
I am getting the following two errors ([full log here](https://bpaste.net/show/b75471900561)):

```
/var/tmp/portage/dev-python/fslpy-1.11.1/work/fslpy-1.11.1/tests/test_vest.py:169: RuntimeWarning: invalid value encountered in divide
  dnorm   = (d - d.min()) / (d.max() - d.min())
/var/tmp/portage/dev-python/fslpy-1.11.1/work/fslpy-1.11.1/fsl/data/vest.py:66: RuntimeWarning: invalid value encountered in divide
  return (colours - cmin) / (cmax - cmin)
```

Any idea what's wrong? To me it looks like a display issue... The program is getting a virtual display for the test phase about which I don't know much.

The tests are being run with:

```
virtx pytest -m "not (dicomtest or fsltest)" --verbose || die
```

(wherw virtx provides the sandbox virtual display) 

@pauldmccarthy can you give me a hand?

**Comment by pauldmccarthy** [comment]
They're warnings which can be ignored - they're triggered by a test which intentionally passes in bad values, and expects bad values out.

**Comment by TheChymera** [comment]
@pauldmccarthy but as you can see, the tests still fail. This is also the case if I run it manually from the terminal. Any ideas why and what I can do about it?

**Comment by pauldmccarthy** [comment]
Your log suggests that all the tests passed - I have no idea why it crashed. Have you tried with xvfb-run instead of virtx? I've never heard of nor used virtx, and can't find much information about it online - mind giving me a link to its home page?

**Comment by TheChymera** [comment]
@pauldmccarthy ok, two updates:

1. It's probably unrelated to the display. I tried to delete the test and the [suite still fails](http://bpaste.net/show/07868a9b20ca). The key snippet might more probably be: `Fatal Python error: deallocating None`

2. If you are still curious about `virtx`, it is a [wrapper from Portage (the Gentoo Linux package manager)](https://github.com/gentoo/gentoo/blob/958b7aed7ec5f7fe104170da0b12227af7979055/eclass/virtualx.eclass#L117) which uses xvfb while making sure things are sandboxed properly.

**Comment by pauldmccarthy** [comment]
The tests are all passing, and those vest warnings have nothing to do with the crash. The `Fatal Python error: deallocating None` is coming from some lower level code - nothing to do with me, I'm afraid.

**Comment by TheChymera** [comment]
Ok, I was unable to get any feedback on this, so for the time being the tests are restricted. Given that ot likely is unrelated to your package specifically I guess we can close this.

**Comment by TheChymera** [comment]
Just for the record, in the mean time (which is as of `=fsply-2.6.2`, and heaps of updated deps) this is no longer an issue for the Gentoo Linux package.
