### ISSUE TITLE
Skip test module installation

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fslpy#6]
Trying to version bump fslpy for Gentoo Linux. I get the following [build.log](https://github.com/pauldmccarthy/fslpy/files/3805523/build.log), of which the crux appears to be an autodetected failure by the Gentoo wrapper:

```
Installing resample_image script to /var/tmp/portage/dev-python/fslpy-2.6.2/image/_python3.6/usr/lib/python-exec/python3.6
 * ERROR: dev-python/fslpy-2.6.2::chymeric failed (install phase):
 *   Package installs 'tests' package which is forbidden and likely a bug in the build system.
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_install
 *   environment, line 2771:  Called distutils-r1_src_install
 *   environment, line  981:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_install'
 *   environment, line  462:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 2312:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 1672:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 1670:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line  674:  Called distutils-r1_run_phase 'distutils-r1_python_install'
 *   environment, line  949:  Called distutils-r1_python_install
 *   environment, line  867:  Called die
 * The specific snippet of code:
 *               die "Package installs '${p}' package which is forbidden and likely a bug in the build system.";
 * 
```

any idea how I can stop the package from installing the test module? I am actually a bit confused, since `setup.py` does not appear to install it, is this somehow specified somewhere else? Or might there be a simple reason why [this line](https://github.com/pauldmccarthy/fslpy/blob/f6161904749db3c40e7b401c046a16966c6dce41/setup.py#L30) is failing?

**Comment by TheChymera** [comment]
Patching some diagnostic print calls into `setup.py` (between the AAAAA and BBBBB calls), and indeed it seems that the test module does not get properly excluded (but the doc module somehow does): [build.log](https://github.com/pauldmccarthy/fslpy/files/3805608/build.log).

Any idea what could be wrong? Maybe because it has submodules?

**Comment by TheChymera** [comment]
Ok, that turns out to have been the issue, submodules don't get excluded by just `exclude=['tests']`, the following patch fixes this:

```
--- a/setup.py	2019-11-04 18:56:47.407791008 +0100
+++ b/setup.py	2019-11-04 20:00:24.844224851 +0100
@@ -29,6 +29,6 @@
 
 packages = find_packages(
-    exclude=('doc', 'tests', 'dist', 'build', 'fslpy.egg-info'))
+    exclude=('doc', 'tests', 'tests.*', 'dist', 'build', 'fslpy.egg-info'))
 
 # Figure out the current fslpy version, as defined in fsl/version.py. We
 # don't want to import the fsl package,  as this may cause build problems.
```

**Comment by pauldmccarthy** [comment]
Oops, it looks like I wasn't using `find_packages` correctly. I might simplify it to:

```
packages = find_packages(include=('fsl', 'fsl.*'))
```

Thanks for figuring that out - I will hopefully be releasing a new version in the next week or so.

**Comment by TheChymera** [comment]
Thanks for considering this :)
