### ISSUE TITLE
Using rtree 0.9.1?

### ISSUE THREAD

**Issue by sanjayankur31** [pauldmccarthy/fslpy#7]
Hello,

rtree saw a new release, 0.9.1: https://pypi.org/project/rtree/  and the Fedora package was updated. Now, fslpy cannot be installed since it wants rtree==0.8.3 (not >=0.8.3).

Will fslpy work with 0.9.1 too?

Thanks,

**Comment by pauldmccarthy** [comment]
Hmm, I had a reason for pinning it, but it doesn't come to mind.  `rtree` is not a direct dependency of `fslpy` - it is required by `trimesh`.

I may be able to get a release out over the next couple of days - I'll have a play with the new `rtree` and see what happens.

**Comment by sanjayankur31** [comment]
Hello,

I hope you had a good break @pauldmccarthy : any ideas on this? (We've now started receiving bugs from users about it).

Cheers,

**Comment by pauldmccarthy** [comment]
Oops, I let this slide - sorry about that. Rudimentary testing (and the rtree changelog) suggests that there's no problem with 0.9.3 - I'll try and get a maintenance release for `fslpy` out next week.

**Comment by sanjayankur31** [comment]
No worries---that's great to hear. Thanks very much :clap:

**Comment by sanjayankur31** [comment]
The new release drops the constraint. Thanks---closing.
